import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { ModalProvider } from "@/components/provider/modal-provider";

export const metadata: Metadata = {
  title: "Medium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <link rel="icon" href="./favicon.ico" />
        <body className="bg-[white]">
          <ModalProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
